### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by nevescode** [mrncst/movie-library#11]
I've tried to reach the IMDB link but it wasn't defined:
http://localhost:3000/movie/546554

Seems to be a problem with "surprise me" feature.

<img width="891" alt="Screen Shot 2019-12-10 at 11 02 24 PM" src="https://user-images.githubusercontent.com/875888/70585024-a202d280-1ba1-11ea-9406-547d1ce4cc53.png">
<img width="989" alt="Screen Shot 2019-12-10 at 11 02 36 PM" src="https://user-images.githubusercontent.com/875888/70585025-a202d280-1ba1-11ea-9bee-f819213254f5.png">

**Comment by mrncst** [comment]
I'll refactor the entire page but it's surely not working as it should.
