### ISSUE TITLE
Spacing and aesthetics at the movie page

### ISSUE THREAD

**Issue by nevescode** [mrncst/movie-library#12]
http://localhost:3000/movie/330457

The content seems too near the right edge

<img width="1280" alt="Screen Shot 2019-12-10 at 11 03 51 PM" src="https://user-images.githubusercontent.com/875888/70585190-353c0800-1ba2-11ea-80d7-5209627bb445.png">

**Comment by mrncst** [comment]
I removed the spacing, maybe it seems better now.
